// app/lib/events.js

export const EVENTS = [
  // ENERO / FEBRERO
  {
    id: 1,
    title: "My Chemical Romance",
    category: "Rock",
    date: "29 de enero de 2026, 21:00",
    location: "Estadio Bicentenario de La Florida, Santiago",
  },
  {
    id: 2,
    title: "Chayanne",
    category: "Pop Latino",
    date: "7 de febrero de 2026, 21:00",
    location: "Estadio Ester Roa, Concepción",
  },
  {
    id: 3,
    title: "Chayanne",
    category: "Pop Latino",
    date: "11 de febrero de 2026, 21:00",
    location: "Estadio Nacional de Chile, Santiago",
  },
  {
    id: 4,
    title: "Chayanne",
    category: "Pop Latino",
    date: "14 de febrero de 2026, 21:00",
    location: "Estadio Sausalito, Viña del Mar",
  },
  {
    id: 5,
    title: "Doja Cat",
    category: "Pop / Hip Hop",
    date: "10 de febrero de 2026, 21:00",
    location: "Movistar Arena, Santiago",
  },
  {
    id: 6,
    title: "Jason Mraz",
    category: "Pop / Folk",
    date: "25 de febrero de 2026, 21:00",
    location: "Teatro Caupolicán, Santiago",
  },
  {
    id: 7,
    title: "Alejandro Sanz",
    category: "Pop",
    date: "28 de febrero de 2026, 21:00",
    location: "Estadio Bicentenario de La Florida, Santiago",
  },

  // MARZO
  {
    id: 8,
    title: "Lollapalooza Chile 2026",
    category: "Festival",
    date: "13–15 de marzo de 2026",
    location: "Parque O'Higgins, Santiago",
  },
  {
    id: 9,
    title: "AC/DC",
    category: "Rock",
    date: "11 de marzo de 2026, 19:00",
    location: "Parque Estadio Nacional, Santiago",
  },
  {
    id: 10,
    title: "AC/DC",
    category: "Rock",
    date: "15 de marzo de 2026, 19:00",
    location: "Parque Estadio Nacional, Santiago",
  },
  {
    id: 11,
    title: "Soda Stereo",
    category: "Rock",
    date: "26 de marzo de 2026, 21:00",
    location: "Movistar Arena, Santiago",
  },
  {
    id: 12,
    title: "Soda Stereo",
    category: "Rock",
    date: "27 de marzo de 2026, 21:00",
    location: "Movistar Arena, Santiago",
  },
  {
    id: 13,
    title: "Soda Stereo",
    category: "Rock",
    date: "28 de marzo de 2026, 21:00",
    location: "Movistar Arena, Santiago",
  },
  {
    id: 14,
    title: "Pennywise",
    category: "Punk",
    date: "20 de marzo de 2026, 21:00",
    location: "Teatro Caupolicán, Santiago",
  },
  {
    id: 15,
    title: "Kali Uchis",
    category: "Pop / R&B",
    date: "11 de marzo de 2026, 21:00",
    location: "Parque Deportivo Estadio Nacional, Santiago",
  },

  // ABRIL
  {
    id: 16,
    title: "Laura Pausini",
    category: "Pop",
    date: "15 de abril de 2026, 20:00",
    location: "Movistar Arena, Santiago",
  },
  {
    id: 17,
    title: "Laura Pausini",
    category: "Pop",
    date: "16 de abril de 2026, 20:00",
    location: "Movistar Arena, Santiago",
  },
  {
    id: 18,
    title: "Mac DeMarco",
    category: "Indie",
    date: "18 de abril de 2026, 19:00",
    location: "Teatro Caupolicán, Santiago",
  },
  {
    id: 19,
    title: "Mac DeMarco",
    category: "Indie",
    date: "19 de abril de 2026, 21:00",
    location: "Teatro Caupolicán, Santiago",
  },
  {
    id: 20,
    title: "Ysy A",
    category: "Trap",
    date: "1 de abril de 2026, 21:00",
    location: "Espacio Riesco, Santiago",
  },
  {
    id: 21,
    title: "Respira Festival",
    category: "Festival",
    date: "3 de abril de 2026",
    location: "Movistar Arena, Santiago",
  },
  {
    id: 22,
    title: "Red Bull Batalla - Final Internacional 2026",
    category: "Freestyle",
    date: "11 de abril de 2026",
    location: "Movistar Arena, Santiago",
  },
  {
    id: 23,
    title: "Black Label Society",
    category: "Metal",
    date: "30 de abril de 2026, 21:00",
    location: "Teatro Coliseo, Santiago",
  },
  {
    id: 24,
    title: "Ill Niño",
    category: "Metal",
    date: "26 de abril de 2026, 21:00",
    location: "Teatro Cariola, Santiago",
  },
  {
    id: 25,
    title: "Feuerschwanz",
    category: "Metal",
    date: "21 de abril de 2026, 21:00",
    location: "Teatro Cariola, Santiago",
  },

  // MAYO y otros
  {
    id: 26,
    title: "Pimpinela",
    category: "Baladas",
    date: "17 de mayo de 2026, 21:00",
    location: "Movistar Arena, Santiago",
  },
  {
    id: 27,
    title: "P.O.D.",
    category: "Rock / Metal",
    date: "4 de mayo de 2026, 20:00",
    location: "Movistar Arena, Santiago",
  },
  {
    id: 28,
    title: "GALNERYUS",
    category: "Metal",
    date: "13 de febrero de 2026, 21:00",
    location: "Teatro Cariola, Santiago",
  },
];
